<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CodesignKey>Apple Distribution: Pavel Zheltiakov (47FT8D5L9N)</CodesignKey>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ava3D.Demo\Ava3D.Demo.csproj" />
  </ItemGroup>
</Project>
